### ISSUE TITLE
[ERROR] class file for com.microsoft.graph.httpcore.IAuthenticationProvider not found

### ISSUE THREAD

**Issue by skakanigit** [microsoftgraph/msgraph-sdk-java-auth#12]
Please update readme.md file with correct version number. com.microsoft.graph.httpcore.IAuthenticationProvider class name was renamed to ICoreAuthentication Provider in msgraph-sdk-java-core library but where as ClientCredentialProvider is still pointing older version

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.808 s
[INFO] Finished at: 2019-04-02T11:10:23-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project outlookconnector: Compilation failure
[ERROR] /Users/skakani/Documents/codeRepo/neuron/code/backend/outlookconnector/src/main/java/org/neuron/AuthHandler.java:[29,59] cannot access com.microsoft.graph.httpcore.IAuthenticationProvider
[ERROR]   class file for com.microsoft.graph.httpcore.IAuthenticationProvider not found

**Comment by NakulSabharwal** [comment]
@skakanigit Thanks for reporting this issue. Most probably your issue is because of caching. If you are using eclipse right-click on project folder in eclipse->gradle->Refresh Gradle Project
If using intellij->File->Invalidate cache and restart. Please reply if you are still facing this issue.

**Comment by skakanigit** [comment]
Thank you for the response @NakulSabharwal . I am still facing the issue even after doing cache invalidation. Also, I am building my application externally using maven and I don't think the issue is  related to IntelliJ internal caching.

**Comment by NakulSabharwal** [comment]
@skakanigit I am not able to repro your issue. Can you try using Auth library in a new project and see if same error comes ? Try deleting C:\Users\YOUR_USERNAME\.gradle\caches\modules-2\files-2.1\com.microsoft.graph\microsoft-graph-auth\0.1.0-SNAPSHOT then start building again.

**Comment by NakulSabharwal** [comment]
@skakanigit Closing this issue since we are not able to repro it. Pls reopen it if you are still facing same issue. Thanks.

**Comment by kris96** [comment]
Hi, 
I am facing the same issue... 
IntelliJ indicate this error message:

`authenticationProvider
(com.microsoft.graph.authentication.IAuthenticationProvider)
in Builder cannot be applied
to
(com.microsoft.graph.auth.confidentialClient.AuthorizationCodeProvider)
`

for this code (from README, 4.1 Authorization code provider):  
```
AuthorizationCodeProvider authProvider = new AuthorizationCodeProvider("6731de76-14a6-49ae-97bc-6eba6914391e",         Arrays.asList("https://graph.microsoft.com/user.read","https://graph.microsoft.com/Mail.ReadWrite"),
                authorizationCode,
                "http://localhost/myapp/",
                NationalCloud.Global,
                "common",
                "JqQX2PNo9bpM0uEihUPzyrh");


IGraphServiceClient graphClient = 
	GraphServiceClient
	.builder()
	.authenticationProvider(authProvider)
	.buildClient();
```

And failed with message: 

`Error:(66, 17) java: cannot access com.microsoft.graph.httpcore.IAuthenticationProvider
  class file for com.microsoft.graph.httpcore.IAuthenticationProvider not found`

**Comment by LeonStemerdink** [comment]
My issue was needing the following dependency when using Maven:

```
		<dependency>
			<groupId>com.microsoft.graph</groupId>
			<artifactId>microsoft-graph-core</artifactId>
			<version>1.0.0</version>
		</dependency>
```
Include this in your pom and it should work. It contains the missing class.

**Comment by JairoCordero** [comment]
this is due to com.microsoft.graph.0.1.0-SNAPSHOT has not been updated.

AuthorizationCodeProvider class is pointing to com.microsoft.graph.httpcore.IAuthenticationProvider

I just downloaded the source code of msgraph-sdk-java-auth, created my jar, and put it on my project. ERROR has gone

**Comment by ViktorFefilov** [comment]
@NakulSabharwal this issue should be reopen

**Comment by rafi-m** [comment]
@NakulSabharwal i still face this issue as there is no class named IAuthenticationProvider in com.microsoft.graph.httpcore. 

@JairoCordero do you mind giving the edited jar file for time being?

**Comment by dbudim** [comment]
Hi guys! Will be IAuthenticationProvider moved to correct package in msgraph-sdk-java-auth ?

**Comment by jski-root** [comment]
Hello. I am getting the same issue. when will maven be updated with the correction?

**Comment by pepavesely** [comment]
The one following your README at https://github.com/microsoftgraph/msgraph-sdk-java-auth will end up with following pom: 

            <dependency>
			<groupId>com.microsoft.graph</groupId>
			<artifactId>microsoft-graph-core</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.graph</groupId>
			<artifactId>microsoft-graph-auth</artifactId>
			<version>0.1.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.graph</groupId>
			<artifactId>microsoft-graph</artifactId>
			<version>1.5.0</version>
		</dependency>

		<profile>
			<id>allow-snapshots</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<repositories>
				<repository>
					<id>snapshots-repo</id>
					<url>https://oss.sonatype.org/content/repositories/snapshots</url>
					<releases>
						<enabled>false</enabled>
					</releases>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
				</repository>
			</repositories>
		</profile>

And also with an error:
**Failed to instantiate [com.frequentis.leosphere.windcollector.service.DownloadDataService]: Constructor threw exception; nested exception is java.lang.Error: Unresolved compilation problem: 
	The type com.microsoft.graph.httpcore.IAuthenticationProvider cannot be resolved. It is indirectly referenced from required .class files**

IMHO this issue should be re-opened.

**Comment by mvreijn** [comment]
There is a mismatch between two classes: 

- `com.microsoft.graph.auth.confidentialClient.ClientCredentialProvider` uses `com.microsoft.graph.httpcore.IAuthenticationProvider`
- `com.microsoft.graph.requests.extensions.GraphServiceClient` uses `com.microsoft.graph.authentication.IAuthenticationProvider`

This means that they are not compatible anymore; the builder method `GraphServiceClient.Builder.authenticationProvider(IAuthenticationProvider authenticationProvider)` cannot be satisfied anymore. 

The solution is to recompile **microsoft-graph-auth** against the new core library.

**Comment by NakulSabharwal** [comment]
@bilalgce Could you look into this issue.

**Comment by bilalgce** [comment]
Thanks for reporting this issue. We're looking into this.

**Comment by einue** [comment]
@bilalgce I get the same error. When will the maven dependency will be updated?

**Comment by kumbhaj** [comment]
can anyone provide the JAR microsoft-graph-auth

**Comment by remyadj** [comment]
@bilalgce Still facing the issue. Can you please help in providing the solution?

**Comment by victormarcus** [comment]
You need to make a JAR from the source code. Use it with microsoft-graph-1.7 and microsoft-graph-core-1.0.0
[microsoft-graph-auth-jar.zip](https://github.com/microsoftgraph/msgraph-sdk-java-auth/files/4113283/microsoft-graph-auth-jar.zip)

**Comment by maxstreifeneder** [comment]
any updates?

**Comment by victormarcus** [comment]
@maxstreifeneder I guess this is still in development

**Comment by debarshri** [comment]
This problem can be solved as follows. 


```package one.trueorigin.integrations.model.integrations;

import com.microsoft.graph.auth.AuthConstants;
import com.microsoft.graph.auth.BaseAuthentication;
import com.microsoft.graph.auth.enums.NationalCloud;
import com.microsoft.graph.authentication.IAuthenticationProvider;
import com.microsoft.graph.http.IHttpRequest;
import org.apache.oltu.oauth2.client.OAuthClient;
import org.apache.oltu.oauth2.client.URLConnectionClient;
import org.apache.oltu.oauth2.client.request.OAuthClientRequest;
import org.apache.oltu.oauth2.common.exception.OAuthProblemException;
import org.apache.oltu.oauth2.common.exception.OAuthSystemException;
import org.apache.oltu.oauth2.common.message.types.GrantType;

import java.util.List;

public class Office365Provider extends BaseAuthentication implements IAuthenticationProvider {

    public Office365Provider(List<String> scopes, String clientId, String authority, String redirectUri, NationalCloud nationalCloud, String tenant, String clientSecret) {
        super(scopes, clientId, authority, redirectUri, nationalCloud, tenant, clientSecret);
    }

    @Override
    public void authenticateRequest(IHttpRequest request) {

        try {
            String accessToken = null;
            long duration = System.currentTimeMillis() - getStartTime();
            if(getResponse()!=null && duration>0 && duration< getResponse().getExpiresIn()*1000) {
                accessToken = getResponse().getAccessToken();
            } else {
                OAuthClientRequest authRequest = getTokenRequestMessage();
                accessToken = getAccessTokenNewRequest(authRequest);
            }
            request.addHeader(AuthConstants.AUTHORIZATION_HEADER, AuthConstants.BEARER + accessToken);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private OAuthClientRequest getTokenRequestMessage() throws OAuthSystemException {
        String tokenUrl = getAuthority() + AuthConstants.TOKEN_ENDPOINT;
        OAuthClientRequest.TokenRequestBuilder token = OAuthClientRequest.
                tokenLocation(tokenUrl)
                .setClientId(getClientId())
                .setGrantType(GrantType.CLIENT_CREDENTIALS)
                .setScope(getScopesAsString());
        if(getClientSecret() != null) {
            token.setClientSecret(getClientSecret());
        }
        return token.buildBodyMessage();
    }

    private String getAccessTokenNewRequest(OAuthClientRequest request) throws OAuthSystemException, OAuthProblemException {
        OAuthClient oAuthClient = new OAuthClient(new URLConnectionClient());
        setStartTime(System.currentTimeMillis());
        setResponse(oAuthClient.accessToken(request));
        return getResponse().getAccessToken();
    }
}
```

This is re-implementing of ClientCredentialProvider. You can do the same for other providers.

**Comment by vnukasani** [comment]
I think still issue persists. 

I mean below class not found in  microsoft-graph-auth-0.1.0-SNAPSHOT

ERROR] class file for com.microsoft.graph.httpcore.IAuthenticationProvider

**Comment by debarshri** [comment]
@vnukasani  If you are using maven, then you have to add this to your pom.xml file.
This will solve the missing dependency problem.
```
        <dependency>
		<groupId>com.microsoft.graph</groupId>
		<artifactId>microsoft-graph-core</artifactId>
		<version>1.0.0</version>
	</dependency>
	<dependency>
		<groupId>com.microsoft.graph</groupId>
		<artifactId>microsoft-graph-auth</artifactId>
		<version>0.1.0-SNAPSHOT</version>
	</dependency>
	<dependency>
		<groupId>com.microsoft.graph</groupId>
		<artifactId>microsoft-graph</artifactId>
		<version>1.5.0</version>
	</dependency>

	<profile>
		<id>allow-snapshots</id>
		<activation>
			<activeByDefault>true</activeByDefault>
		</activation>
		<repositories>
			<repository>
				<id>snapshots-repo</id>
				<url>https://oss.sonatype.org/content/repositories/snapshots</url>
				<releases>
					<enabled>false</enabled>
				</releases>
				<snapshots>
					<enabled>true</enabled>
				</snapshots>
			</repository>
		</repositories>
	</profile>
```

**Comment by fstuff** [comment]
Hello, 

I encountered this same issue tonight, and was able to resolve it by refreshing the snapshot cache.  In Eclipse, I right-clicked on the top-level project.  Then I selected Maven, and then Update Project.  Then I enabled the checkbox for "Update project configuration from pom.xml:

![image](https://user-images.githubusercontent.com/1115274/80783951-4aeda200-8b30-11ea-8cf1-4ef24f0c16bc.png)

HTH.

**Comment by fstuff** [comment]
Immediately after I posted my comment, the behavior re-appeared.  I used the following maven command:`mvn dependency:purge-local-repository` which I found from here https://stackoverflow.com/questions/7408545/how-do-you-clear-apache-mavens-cache

I think that finally did it....
