### ISSUE TITLE
Rel version of microsoft-graph-auth

### ISSUE THREAD

**Issue by nshowkath** [microsoftgraph/msgraph-sdk-java-auth#19]
Hi   Sabharwal,

Currently microsoft-graph-auth has 0.1.0-SNAPSHOT version & we are building (mvn)  locally to consume. Project needs this dependency to be available on central repository. 
Just curios to know when  will be microsoft-graph-auth  rel version available  
As you know microsoft-graph , microsoft-graph-core has release versions 
https://mvnrepository.com/artifact/com.microsoft.graph

Regards,
Showkath.

**Comment by darrelmiller** [comment]
Hey nshowkath,

We are working towards using MSAL as our primary authentication library for our SDKs.  Therefore we need to wait until the [MSAL library](https://github.com/AzureAD/microsoft-authentication-library-for-java) is out of preview before our auth provider can come out of preview.

**Comment by nshowkath** [comment]
Hi darrelmiller ,
Thanks for your reply .So cant we use for production till Microsoft releases  MSAL library ?
https://github.com/microsoftgraph/msgraph-sdk-java-auth
<dependency>
	<groupId>com.microsoft.graph</groupId>
	<artifactId>microsoft-graph-auth</artifactId>
	<version>0.1.0-SNAPSHOT</version>
</dependency>

Note : One option is we have to import this git project source code & add to our solution . 
Again it needs approvals in our organization.


Regards,
Showkath.
