### ISSUE TITLE
The type com.microsoft.graph.httpcore.IAuthenticationProvider cannot be resolved. It is indirectly referenced from required .class files

### ISSUE THREAD

**Issue by poovaraj** [microsoftgraph/msgraph-sdk-java-auth#22]
It is throwing below error message.

"The type com.microsoft.graph.httpcore.IAuthenticationProvider cannot be resolved. It is indirectly referenced from required .class files"

`
<dependency>
	<groupId>com.microsoft.graph</groupId>
	<artifactId>microsoft-graph-auth</artifactId>
	<version>0.1.0-SNAPSHOT</version>
</dependency>
Add in project

<profiles>
  <profile>
     <id>allow-snapshots</id>
        <activation><activeByDefault>true</activeByDefault></activation>
     <repositories>
       <repository>
         <id>snapshots-repo</id>
         <url>https://oss.sonatype.org/content/repositories/snapshots</url>
         <releases><enabled>false</enabled></releases>
         <snapshots><enabled>true</enabled></snapshots>
       </repository>
     </repositories>
   </profile>
</profiles>`

**Comment by briatayan** [comment]
I'm encountering this issue as well, seems like it's referencing a class that no longer exists.

**Comment by darrelmiller** [comment]
The IAuthenticationProvider interface is here https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/main/java/com/microsoft/graph/authentication/IAuthenticationProvider.java

This library is a companion library that works with the Java SDK.

**Comment by michaltc** [comment]
I'm following example https://github.com/microsoftgraph/java-spring-webhooks-sample, Gradle variant compiles but the Maven one does not.

Hotfix for the Maven variant is to replace `<repository>` 
 `https://oss.sonatype.org/content/repositories/snapshots` by `http://oss.jfrog.org/artifactory/oss-snapshot-local` in `pom.xml`. This one is referenced in `build.gradle` and probably contains a newer variant of `com.microsoft.graph:microsoft-graph-auth:0.1.0-SNAPSHOT`.

**Comment by debarshri** [comment]
see #12

**Comment by tech-behemoth** [comment]
When will this fix be released? One year to fix this issue, really? This library is an embarassment to Microsoft, much like Windows Phone and Skype. In fact the entire Azure cloud service is crappy as hell. Unfortunately I'am working on a project that has no option but to use Microsoft Graph API. But, if I were to choose, never in my life I would choose Azure cloud service. The fact that it is so poorly documented is something inexplicable to me. Microsoft should know way better....

**Comment by MIchaelMainer** [comment]
This is now available in microsoft-graph-auth 0.2.0-SNAPSHOT. Agreed, this should have been done a long time ago.
