### ISSUE TITLE
Is there a non snapshot version for this library?

### ISSUE THREAD

**Issue by pula2000** [microsoftgraph/msgraph-sdk-java-auth#23]

**Comment by MIchaelMainer** [comment]
We are working to adopt the MSAL library for authentication. The current implementation was a temporary solution until MSAL was ready.

**Comment by FelixJongleur42** [comment]
Is MSAL ready now? https://github.com/AzureAD/microsoft-authentication-library-for-java/releases

**Comment by jennyqq** [comment]
> We are working to adopt the MSAL library for authentication. The current implementation was a temporary solution until MSAL was ready.
When the MSAL lib can incorporate the authentication providers which are in the temp solution?
