### ISSUE TITLE
[ERROR] class file for com.microsoft.graph.httpcore.IAuthenticationProvider not found

### ISSUE THREAD

**Issue by AMarquis1** [microsoftgraph/msgraph-sdk-java-auth#24]
The maven dependency need to be updated.It is not usable until then. ClientCredentialProvider.java is implemeting IAuthenticationProvider, but this class changed location in the project since last Graph.core update.
https://github.com/microsoftgraph/msgraph-sdk-java-auth/issues/17#issuecomment-553377748 
https://github.com/microsoftgraph/msgraph-sdk-java-auth/issues/15#issue-463519542
https://github.com/microsoftgraph/msgraph-sdk-java-auth/issues/18#issue-481841023
https://github.com/microsoftgraph/msgraph-sdk-java-auth/issues/22#issue-529333672
pointed the same situation

**Comment by victormarcus** [comment]
Create JAR from the project source

**Comment by debarshri** [comment]
see #12

**Comment by MIchaelMainer** [comment]
This is now available in microsoft-graph-auth 0.2.0-SNAPSHOT.
