### ISSUE TITLE
I am trying to use microsoft graph auth library preview. I amable to initialize the graphClient but unable to get data.I am getting unauthorized 401.

### ISSUE THREAD

**Issue by victormarcus** [microsoftgraph/msgraph-sdk-java-auth#25]
"code": "InvalidAuthenticationToken", "message": "CompactToken parsing failed with error code: 80049217",
`List<String> scopes = new ArrayList<String>();
    scopes.add("User.Read.All");

ClientCredentialProvider authProvider = new ClientCredentialProvider(app-Id, 
            scopes_list,
            client-Secret,
            tenantId, NationalCloud.Global);

IgraphClient graphClient = GraphServiceClient.builder().authenticationProvider(authProvider).logger(logger)
                .buildClient();

IUserCollectionPage users = graphClient.users()
            .buildRequest()
            .get();
    List<User> usersList = users.getCurrentPage();
    for(User user : usersList) {
        System.out.println(user.displayName);
    }`

**Comment by MIchaelMainer** [comment]
Answered on StackOverflow.

https://stackoverflow.com/questions/59987033/using-new-microsoft-graph-auth-library-java-sdk-gives-unauthorized-error

**Comment by victormarcus** [comment]
@MIchaelMainer  I tried the solution given in   [ https://stackoverflow.com/questions/59987033/using-new-microsoft-graph-auth-library-java-sdk-gives-unauthorized-error](url).

`List<String> scopes = new ArrayList<String>();
 scopes.add("https://graph.microsoft.com/.default"); 

List<String> scopes = new ArrayList<String>();
scopes.add(".default");`

I tried above two with all the permissions granted admin consent.  I am still  getting the same error.

![Capture](https://user-images.githubusercontent.com/36796254/73514491-f09d5200-4417-11ea-9fb0-c91f3882241f.PNG)

**Comment by kumbhaj** [comment]
@NakulSabharwal Please address my issue.
