### ISSUE TITLE
Better to provide maven version with com.microsoft.graph.httpcore.IAuthenticationProvider class file

### ISSUE THREAD

**Issue by vnukasani** [microsoftgraph/msgraph-sdk-java-auth#28]
Dear Team,

It's better to provide maven version with com.microsoft.graph.httpcore.IAuthenticationProvider class file  as most of developers are using maven rather than gradle.

Even i could not get  com.microsoft.graph.httpcore.IAuthenticationProvider class in the below maven dependency.

<dependency>
		<groupId>com.microsoft.graph</groupId>
		<artifactId>microsoft-graph-auth</artifactId>
		<version>0.1.0-SNAPSHOT</version>
</dependency>

It will be great and very helpful if you provide  com.microsoft.graph.httpcore.IAuthenticationProvider class in the next maven release version. 

Thanks!

**Comment by debarshri** [comment]
related to #12

**Comment by vtiwari227** [comment]
@MIchaelMainer @baywet  I think, the maven build is still don't have merge changes from today. Can you publish changes to maven ?

**Comment by baywet** [comment]
@MIchaelMainer is working on it from our last chat offline. We'll post an update on the pull requests and issues once it's done

**Comment by MIchaelMainer** [comment]
@vtiwari227 @debarshri @vnukasani

A snaphot has been published microsoft-graph-auth 0.2.0-SNAPSHOT.

**Comment by vtiwari227** [comment]
@baywet @MIchaelMainer Not sure, if related but pulling 0.2.0-SNAPSHOT from maven is failing  because it's looking for 1.0.1 for ms-graph-core and that is returning  404.

```not found: https://repo1.maven.org/maven2/com/microsoft/graph/microsoft-graph-core/1.0.1/microsoft-graph-core-1.0.1.pom
not found: https://repo1.maven.org/maven2/com/microsoft/graph/microsoft-graph-core/1.0.1/microsoft-graph-core-1.0.1.pom

**Comment by baywet** [comment]
Yep it's available on bintray https://dl.bintray.com/microsoftgraph/Maven/com/microsoft/graph/microsoft-graph-core/1.0.1/microsoft-graph-core-1.0.1.jar

I already have an issue open about the fact that it's not published on Central
https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/30

Maybe @MIchaelMainer can help with that as well.

**Comment by vtiwari227** [comment]
@metathinker Can you help promoting ms-graph-core-1.0.1 to maven so we can void having bintray dependency. thanks 
and also do you guys have a timeline, when there will be a stable (non snapshot) version of this lib( msgraph-sdk-java-auth) will be released so we no longer need to add sonatype in build.sbt. thanks for the help

**Comment by baywet** [comment]
@vtiwari227 let's move this part of the discussion over the issue I already created there? the work in the repo we're currently in has been done, now it's a matter of another repo.

**Comment by metathinker** [comment]
> @metathinker Can you help promoting ms-graph-core-1.0.1 to maven so we can void having bintray dependency. thanks
> and also do you guys have a timeline, when there will be a stable (non snapshot) version of this lib( msgraph-sdk-java-auth) will be released so we no longer need to add sonatype in build.sbt. thanks for the help

Sorry, unfortunately I don't work in this area. I think @baywet has you covered, though.
