### ISSUE TITLE
Create user error: password complexity

### ISSUE THREAD

**Issue by marcosvidolin** [microsoftgraph/msgraph-sdk-java-auth#36]
Hi,

I got the following error when I try to create a new user using graph api. I already set the password policies to **DisablePasswordExpiration** and **DisableStrongPassword**

The users may have a weak password because they came from a legacy IdP. I'm migrating all of then from a legacy IdP to the Azure B2C.

Is there an extra configuration that I missed?

> Error message: The specified password does not comply with password complexity requirements. Please provide a different password.

That is my code:

```java
public static void gapi() {

	ClientCredentialProvider authProvider =
		new ClientCredentialProvider(CLIENT_ID, SCOPES, CLIENT_SECRET, TENANT_GUID, NATIONAL_CLOUD);
	IGraphServiceClient graphClient = GraphServiceClient
		.builder()
		.authenticationProvider(authProvider)
		.buildClient();

	IUserCollectionRequestBuilder usersRequest = graphClient.users();
	usersRequest.buildRequest().post(getFakeUser());
}

private static User getFakeUser() {
	User user = new User();
	user.accountEnabled = true;
	user.displayName = "Test";
	user.givenName = "Test";
	user.userPrincipalName = "test@test.onmicrosoft.com";
	user.mail = "test@test.com";
	user.mailNickname = "Vidolin";
	user.surname = "marcosvidolin";

	PasswordProfile pass = new PasswordProfile();
	pass.forceChangePasswordNextSignIn = false;
	pass.forceChangePasswordNextSignInWithMfa = false;
	pass.password = "1234";
	user.passwordProfile = pass;
	user.passwordPolicies = "DisablePasswordExpiration, DisableStrongPassword";

	return user;
}
```
Tks

**Comment by MIchaelMainer** [comment]
Thank you for your question. Please post your question to [StackOverflow](https://stackoverflow.com/questions/tagged/microsoft-graph) and tag your post with
the [microsoft-graph] tag. Make sure you include the following information:
1. Tell us what you've tried. Include detailed reproduction steps.
2. Link to the documentation and samples that you've used as reference.
3. Provide an example HTTP request and response that shows the call being made. Make sure you scrub your example of any secrets.

**Comment by MIchaelMainer** [comment]
Provide a link to your SO post in this issue.
