### ISSUE TITLE
UsernamePasswordProvider (Delete Me)

### ISSUE THREAD

**Issue by abbeycode** [microsoftgraph/msgraph-sdk-java-auth#54]
Please delete this issue for me. I accidentally overshared in the original revision, and opened a new issue with the contents redacted.

**Comment by abbeycode** [comment]
Are you able to delete this post instead of only closing it? There’s confidential info in the edit history. Sorry for the hassle.

**Comment by baywet** [comment]
I'm not but it might be a permission issue. @MIchaelMainer can you delete this post?

**Comment by abbeycode** [comment]
@MIchaelMainer do you have delete permissions on this one?
