### ISSUE TITLE
OAuthProblemException{error='invalid_grant', description='AADSTS50148: The code_verifier does not match the code_challenge supplied in the authorization request for PKCE.

### ISSUE THREAD

**Issue by amitdctm** [microsoftgraph/msgraph-sdk-java-auth#65]
While using below example API, I get the error. How can I pass the code_verifier and code_challenge in the API?

**Error**:

OAuthProblemException{error='invalid_grant', description='AADSTS50148: The code_verifier does not match the code_challenge supplied in the authorization request for PKCE.

**Code**:

AuthorizationCodeProvider authProvider = new AuthorizationCodeProvider("client_id",
				Arrays.asList("https://graph.microsoft.com/user.read", "https://graph.microsoft.com/Mail.ReadWrite"),
				authorizationCode, "https://xcpapp/msgraph/", NationalCloud.Global, "common",
				"client_secret");

Is there an Authentication Provider where I can pass access token instead of expired OAuth Code?
My App already has access token and refresh tokens to use on Graph SDK. 
[AB#7897](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7897)

**Comment by baywet** [comment]
Hi @amit17051980 
Thanks for reaching out.
Not at the moment. You can however implement ICoreAuthenticationProvider and IAuthenticatationProvider (SDK < 3.0.0-SNAPSHOT) to do so.
We currently have a [preview of the next version of the SDK](https://github.com/microsoftgraph/msgraph-sdk-java/issues/628) out there which features great improvements. A better authentication story is part of those improvement and we rely on azure identity. Should you decide to keep using authorization code, [there's a provider for that](https://docs.microsoft.com/en-us/java/api/overview/azure/identity-readme?view=azure-java-stable). Should you decide to implement your own provider, you now only need to extend [BaseAuthenticationProvider](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/feature/v2/src/main/java/com/microsoft/graph/authentication/BaseAuthenticationProvider.java).
I hope this helps. Let me know if you have further questions.
