### ISSUE TITLE
What is the proper way to use in a multithreading environnement

### ISSUE THREAD

**Issue by rpicot-lecko** [microsoftgraph/msgraph-sdk-java-auth#67]
We tried several strategies, and it seems whatever we do we encounter some bugs. I'd like to post a minimal working example, but it would be better if I know beforehand what is the intended way  to call msgraph api with this lib in a multithreading environment 

```
            graphClient = GraphServiceClient.builder()
                    .authenticationProvider(authProvider)
                    .logger(logger)
                    .buildClient();
```

Each thread is supposed to make this call and use his instance of the graph client ?
Or am I supposed to do that at the startup of the app, then each thread use this unique instance ? (And if it's the case, should I use a semaphore ?)

 
[AB#8060](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8060)

**Comment by baywet** [comment]
Hi @rpicot-leckom
Thanks for reaching out. To properly answer this question I'd need more insights into your application like:
- What kind of application is it? (server, desktop, native)
- How do you authenticate? (which provider do you use?)

In the meantime I also suggest you check out the [v3 work and try the preview](https://github.com/microsoftgraph/msgraph-sdk-java/issues/628). A few of the features that can be interesting for you:

- new authentication providers streamlined with Azure-Identity
- async API returning completable futures, better suited for high-performance solutions
- significant performance improvements

**Comment by rpicot-lecko** [comment]
Thanks for the insights on v3.

For our main task, it's a server running on behalf of a user account

We use a refresh token at start to generate an authentication token and make calls with IAuthenticationProvider.
The relevant line looks like this : 
`request.addHeader("Authorization", "Bearer " + token);`
When we we got everything needed, we shutdown for some time.

Is this the info you needed ?

**Comment by baywet** [comment]
Are you using any of the [authentication providers available in this library](https://github.com/microsoftgraph/msgraph-sdk-java-auth#22-create-an-authentication-provider-object)? if so which one?

Have you seen [this comment](https://github.com/microsoftgraph/msgraph-sdk-java/issues/553#issuecomment-775163943) ? I believe you would be able to achieve better performances with a static reference to the graph client (which in turns would mean using a static reference to okhttp connection pool, which in turn would mean better http connections management). And you could do while "switching context" for users by implementing some kind of provider that uses a callback.

But again, all of that is meant to be simplified with the v3 and the use of Azure-Identity. This library provides token caching, token renewal from the refresh token and more.

**Comment by rpicot-lecko** [comment]
Thanks for the answers.
We already do something close to the comment you linked. That is to say, one graphClient shared among threads, initialized once at startup, manually feeding the request with an access token in the IAuthenticationProvider, (and we do verify that the token is not close to expire before each request, and we do synchronise when necessary)

What we didn't do is putting the graphClient variable as static, and oddly, it improves the situation. Concurrency issues gets way down but some are still here.

We'll do more test and come back

So just to be sure, in the mean time. From what I got in our previous exchange, one graphClient, initialized once and shared among threads is supposed to be a supported workflow ?

**Comment by baywet** [comment]
We recommend consumers to reuse the graphClient as much as possible (considering their authentication requirements and their app design), and yes, it's perfectly fine to have it as a static reference or better yet as a singleton as long as your app is designed in a way it won't "mix contexts" between different users (or as long as it is app only).

If you're still having some multithreading issues, please try the preview of the v3 with the CompletableFuture (Async suffixes) API surface. We stripped all the custom code we had to manage threads in the former callback API surface to rely on native platform capabilities instead.

**Comment by rpicot-lecko** [comment]
Then I guess we have everything we need.
Many thanks for the answers : )
