### ISSUE TITLE
Mockito is added as a compile dependency instead of a test dependency

### ISSUE THREAD

**Issue by lion7** [microsoftgraph/msgraph-sdk-java-auth#7]
https://github.com/microsoftgraph/msgraph-sdk-java-auth/blob/01f9e05842f5977aabe7370fe008b73125d0236a/build.gradle#L23

**Comment by NakulSabharwal** [comment]
@lion7 Thanks for creating this issue. I will create a PR to fix this.

**Comment by lion7** [comment]
Thanks for the quick reply.

On a side note: this library doesn't seem compatible with https://github.com/microsoftgraph/msgraph-sdk-java, even though its only a few weeks old. Is the https://github.com/microsoftgraph/msgraph-sdk-java-core which this library depends on something different?

My use case is to send some email from a Java backend application using my Office 365 subscription. Following the tutorial https://docs.microsoft.com/en-us/graph/outlook-create-send-messages I figured I had to use https://github.com/microsoftgraph/msgraph-sdk-java but with a non-Android authenticator, which eventually led me to this repo ;)

**Comment by lion7** [comment]
I'm probably doing something completely wrong: do I send REST messages direcly using an okhttp `HtpClient` instead of messing around with the SDK?

**Comment by NakulSabharwal** [comment]
@lion7 This auth is currently a pre-release and still under development. Yes, currently this auth is not compatible with [msgraph-sdk-java](https://github.com/microsoftgraph/msgraph-sdk-java). We have build the [java-core (Preview) ]( https://github.com/microsoftgraph/msgraph-sdk-java-core) that will be compatible with this Auth provider. Also, we will be integrating [msgraph-sdk-java](https://github.com/microsoftgraph/msgraph-sdk-java) with [java-core (Preview) ]( https://github.com/microsoftgraph/msgraph-sdk-java-core).
Currently they are separate entity but soon will be integrated.

Thanks

**Comment by NakulSabharwal** [comment]
@lion7 

> I'm probably doing something completely wrong: do I send REST messages direcly using an okhttp HtpClient instead of messing around with the SDK?

You can use [msgraph-sdk-java](https://github.com/microsoftgraph/msgraph-sdk-java) to make rest calls that will provide you with all Models related workloads with very easy request builder pattern. Also, you can use separately our [msgraph-sdk-java-core](https://github.com/microsoftgraph/msgraph-sdk-java-core) that uses OkHttp's http client but also our sdk provides middleware pipeline, custom/default retry, custom/default redirect handlers , auth handlers and batching which gives added advantage of using sdk instead of using simply okhttp.

**Comment by lion7** [comment]
@NakulSabharwal thanks for update and extra information, it is much appreciated. 
I'll try both options and see which 1 suits my needs best. I'll post my findings here later on :)

**Comment by NakulSabharwal** [comment]
@lion7 Do share any problem in usage of  [msgraph-sdk-java](https://github.com/microsoftgraph/msgraph-sdk-java) or [msgraph-sdk-java-core](https://github.com/microsoftgraph/msgraph-sdk-java-core).

**Comment by lion7** [comment]
@NakulSabharwal after playing around a bit with both libraries I decided to stick with the stable and released https://github.com/microsoftgraph/msgraph-sdk-java.
For authentication I copied the `ClientCredentialProvider` in this repository and made it implement the `IAuthenticationProvider` required for the `GraphServiceClient` builder. 
That did the trick and I'm now happily mailing using the Office 365 Exchange server 👍

**Comment by NakulSabharwal** [comment]
@lion7 We have updated this Auth library and binary( 0.1.0-SNAPSHOT ) and now its usable with both [msgraph-sdk-java](https://github.com/microsoftgraph/msgraph-sdk-java) and [msgraph-sdk-java-core](https://github.com/microsoftgraph/msgraph-sdk-java). Please try to use it in your application.

**Comment by lion7** [comment]
I tried it out and it works great with https://github.com/microsoftgraph/msgraph-sdk-java. I don't know if it works https://github.com/microsoftgraph/msgraph-sdk-java because I'm not using that at the moment.
